// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	common_scripts\utility::add_destructible_type_function( "toy_tv_video_monitor", destructible_scripts\toy_tv_video_monitor::main );
}
