// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	common_scripts\utility::add_destructible_type_function( "toy_transformer_small01", destructible_scripts\toy_transformer_small01::main );
	maps\animated_models\mp_frag_crane::main();
}
