// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	maps\animated_models\mp_flooded_water_debris_bob::main();
	maps\animated_models\mp_flooded_water_debris_spiral::main();
	maps\animated_models\mp_flooded_water_street::main();
}
